name: CI

on: [ push ]

env:
    SYMFONY_PHPUNIT_DIR: "$HOME/symfony-bridge/.phpunit"

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: ['7.4', '8.0']

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    ini-values: "memory_limit=-1"
                    php-version: "${{ matrix.php }}"
                    tools: "pecl, cs2pr"

            -   name: Configure matchers
                uses: mheap/phpunit-matcher-action@master

            -   name: Display versions
                run: |
                    php --version
                    php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
                    php -i

            -   name: Install Composer
                uses: php-actions/composer@v1

            -   name: Composer Normalize
                uses: "docker://ergebnis/composer-normalize-action:latest"
                with:
                    args: "--indent-style tab --indent-size 1 --dry-run --ansi"
