name: CI

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2

            -   name: Install Composer
                uses: php-actions/composer@v1

            -   name: Composer Normalize
                uses: "docker://ergebnis/composer-normalize-action:latest"
                with:
                    args: "--indent-style tab --indent-size 1 --dry-run"
